---
wordpress_folder: /var/data/wordpress

# ports
wordpress_port: 8080
wordpress_db_port: 3306

# wordpress db
wordpress_db_database: wordpress
wordpress_db_user: wordpress
wordpress_db_host: "{{ hostvars[groups['wordpress_db'][0]].ansible_default_ipv4.address }}"
